version: "3.8"
services:
  redis:
    image: redis:7.0.6
    container_name: dev_redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server

volumes:
  redis:
    name: dev
